"""
Phase 2.5 driver — country-profiler agent.

Simulates invoking the country-profiler agent once per country:
  1. Writes a supporting script scripts/country_<slug>.py for each country
  2. Runs each profile and collects all six into scripts/country_profiles.md

Countries: México, Colombia, Argentina, Chile, Perú, Brasil
"""

import subprocess
import sys
import unicodedata
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

COUNTRIES = ["México", "Colombia", "Argentina", "Chile", "Perú", "Brasil"]
SCRIPTS_DIR = Path("scripts")
PROFILES_MD = SCRIPTS_DIR / "country_profiles.md"

WRAPPER_TEMPLATE = '''\
"""
Country profile for {country} — generated by the country-profiler agent.
Reads data/latam_finanzas_clean.csv and prints a Markdown profile section.
"""

import sys
sys.stdout.reconfigure(encoding="utf-8")

from _profile_lib import profile_country

if __name__ == "__main__":
    print(profile_country("{country}"))
'''


def slug(name: str) -> str:
    """México -> mexico, Perú -> peru."""
    decomposed = unicodedata.normalize("NFKD", name)
    ascii_name = decomposed.encode("ascii", "ignore").decode("ascii")
    return ascii_name.lower()


def main():
    sections = []
    for country in COUNTRIES:
        script_path = SCRIPTS_DIR / f"country_{slug(country)}.py"
        script_path.write_text(
            WRAPPER_TEMPLATE.format(country=country), encoding="utf-8"
        )
        # Run the per-country script exactly as the agent would.
        result = subprocess.run(
            [sys.executable, str(script_path)],
            capture_output=True, text=True, encoding="utf-8", cwd=".",
        )
        if result.returncode != 0:
            print(f"ERROR profiling {country}:\n{result.stderr}")
            sys.exit(1)
        sections.append(result.stdout.strip())
        print(f"  profiled {country:12s} -> {script_path}")

    combined = (
        "# Country Profiles — Encuesta de Bienestar Financiero LatAm 2025\n\n"
        "_Generated by the `country-profiler` agent from "
        "`data/latam_finanzas_clean.csv`._\n\n"
        + "\n\n---\n\n".join(sections)
        + "\n"
    )
    PROFILES_MD.write_text(combined, encoding="utf-8")
    print(f"\nCollected {len(sections)} profiles -> {PROFILES_MD}")


if __name__ == "__main__":
    main()
