"""
Country profile for Brasil — generated by the country-profiler agent.
Reads data/latam_finanzas_clean.csv and prints a Markdown profile section.
"""

import sys
sys.stdout.reconfigure(encoding="utf-8")

from _profile_lib import profile_country

if __name__ == "__main__":
    print(profile_country("Brasil"))
